The Texas Flag on Turtle Python

import turtle
wn = turtle.Screen()
wn.bgcolor("green")
tony = turtle.Turtle()
tony.penup()
tony.left(180)
tony.fillcolor("white")
tony.forward(200)
tony.right(90)
tony.pendown()
tony.begin_fill()
tony.forward(450)
tony.right(90)
tony.forward(900)
tony.right(90)
tony.forward(450)
tony.right(90)
tony.forward(900)
tony.end_fill()
tony.left(90)
tony.fillcolor("red")
tony.begin_fill()
tony.forward(450)
tony.left(90)
tony.forward(900)
tony.left(90)
tony.forward(450)
tony.left(90)
tony.forward(900)
tony.end_fill()
tony.fillcolor("navyblue")
tony.right(90)
tony.begin_fill()
tony.forward(450)
tony.left(90)
tony.forward(450)
tony.left(90)
tony.forward(900)
tony.left(90)
tony.forward(450)
tony.left(90)
tony.forward(450)
tony.end_fill()
tony.penup()
tony.color("white")
tony.right(180)
tony.forward(128.571)
tony.right(90)
tony.forward(321.429)
tony.right(180)
tony.pendown()
tony.fillcolor("white")
tony.begin_fill()
angle = [36,144,144,144,144]
for i in angle:
    tony.left(i)
    tony.forward(321.429)

tony.end_fill()
turtle.done()
